profile and background image cleanup from cloud
narayan954/dummygram pull request #1108
Opened 2023-08-03 08:21 UTC by Palakkgoyal

This PR closes #1079 
I have done the cleanup for both and also made the function reusable.

2023-08-03 20:58 UTC, narayan954 requested changes
some changes required

2023-08-03 20:58 UTC, narayan954 commented on src/components/EditProfile/index.jsx
> +    const isImgDeleted = deleteImg(userData.avatar)
isn't that an async call and should be awaited? Also, we should be deleting the image only after new one replaces it. you may keep this url in variable and call it after update is successful to free the resources

2023-08-03 20:58 UTC, narayan954 commented on src/pages/Profile/index.jsx
> +      const imgdeleted = deleteImg(bgImageUrl)
same suggestion as before

2023-08-04 06:28 UTC, Palakkgoyal commented
Yes, I was confused about it that I should delete the image before or after.

2023-08-04 08:36 UTC, Palakkgoyal commented
Hey @narayan954 do you know why this error is keep coming?
![Screenshot 2023-08-04 140540](https://github.com/narayan954/dummygram/assets/116902573/35dd97bc-ba50-4589-b934-cfdcff9403a8)

2023-08-04 18:46 UTC, narayan954 commented
> Hey @narayan954 do you know why this error is keep coming? ![Screenshot 2023-08-04 140540](https://user-images.githubusercontent.com/116902573/258368118-35dd97bc-ba50-4589-b934-cfdcff9403a8.png)

need to look into this, step to reproduce this error?

2023-08-05 06:41 UTC, Palakkgoyal commented
> > Hey @narayan954 do you know why this error is keep coming? ![Screenshot 2023-08-04 140540](https://user-images.githubusercontent.com/116902573/258368118-35dd97bc-ba50-4589-b934-cfdcff9403a8.png)
> 
> need to look into this, step to reproduce this error?
> 
> Edit: Fixed this, default firebase rules were not updated

Ohk, thanks.

2023-08-05 08:59 UTC, Palakkgoyal commented
I did the required changes. Can you please check?

2023-08-05 15:46 UTC, narayan954 approved these changes
looks good to me!

2023-08-05 15:48 UTC, merged