bug-fix-1044 alignment issue
narayan954/dummygram pull request #1123
Opened 2023-08-04 07:51 UTC by biplavmz

bug fix for alignment issue  number #1044 

<img width="286" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/6cc91a8c-91fd-4ed8-8d54-d1d1914bc265">

<img width="494" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/fc370bbf-25d0-4988-915b-1608cef61adf">

2023-08-04 21:16 UTC, narayan954 requested changes

2023-08-04 21:16 UTC, narayan954 commented on src/components/Navbar/index.css
> +.search-Contributor{
this is not related to the actual purpose, as we are searching users here instead of contributors. This class is suitable for contributors page

2023-08-04 21:16 UTC, narayan954 commented on src/components/Navbar/index.css
> +  margin-left: 10px;
I doubt we need this now as this component has been updated, can you please check?

2023-08-04 21:16 UTC, narayan954 commented on src/pages/FooterPages/ContributorPage/index.jsx
> +          className="search-input search-Contributor"
you should add this class's css in index.css of contributor page only not in navbar's index.css

2023-08-05 19:37 UTC, biplavmz commented
Hii @narayan954 I have given a changes can you pls check 
Before :-
<img width="321" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/75587623-e63d-4ed6-b63b-9bf51dacdf9d">
 
After :- 
<img width="228" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/439635ff-4673-49a5-bd85-7fc810f4bd6b">

2023-08-06 13:44 UTC, narayan954 approved these changes
looks good to me!

2023-08-06 13:45 UTC, merged