Add bg zoom out effect on scroll
narayan954/dummygram pull request #1133
Opened 2023-08-04 17:17 UTC by Palakkgoyal

This PR closes #1100

2023-08-04 20:44 UTC, narayan954 requested changes
hi @Palakkgoyal this looks awesome but it's not getting reset to original size after we scroll back up, can you please check?
![image](https://github.com/narayan954/dummygram/assets/77617189/ca8e8129-a3bf-4cb4-b44e-bc0d4ab17992)

![image](https://github.com/narayan954/dummygram/assets/77617189/def85988-7caa-4488-a44e-821a48d0c4fa)

2023-08-05 08:25 UTC, Palakkgoyal commented
I did the required changes. This was occuring due to zoom out effect as in the useEffect I had given:
160 - pageYOffset
due to which the initial width and height of the image become 160%.
To solve this I changed it to zoom in instead of zoom out. It works fine now.

2023-08-05 14:23 UTC, narayan954 approved these changes
looks good to me!

2023-08-05 14:23 UTC, narayan954 commented on src/pages/Profile/index.jsx
> +      bg.style.height = 100 + +window.pageYOffset/16 + "%";
pageyoffset is deprecated ,changing to scrollY instead

2023-08-05 14:23 UTC, merged