feat: Upgraded Login form
narayan954/dummygram pull request #1139
Opened 2023-08-05 07:30 UTC by SyedImtiyaz-1

Hello @narayan954 ,
I have upgraded the login form and now it is looking much good.
I have fixed the bugs which was there.

### Fixed List & Upgradation :
- Alignment Issue 
- Overlapping
- Height/Width Issue
- Show Password `svg` Issue
- Added Linear Gradient to the `white background`
- Used Resuable CSS for optimization

### Screenshot 
Light Mode : 
![image](https://github.com/narayan954/dummygram/assets/121503426/935db7b6-33f6-46d5-ac50-66a0b57b3bb6)

DarkMode:
![image](https://github.com/narayan954/dummygram/assets/121503426/77b35288-ede5-4581-8953-f7e1dd6ab7eb)

### It is ready to Merge 👍🏻

2023-08-05 16:13 UTC, SyedImtiyaz-1 commented
@narayan954 kindly review this.

2023-08-05 16:16 UTC, narayan954 commented
> @narayan954 kindly review this.

will do, seeing some issues, like logo has no left padding/margin.
Also login/signup page is looking bad on mobile view
![image](https://github.com/narayan954/dummygram/assets/77617189/845f81c1-b2fd-42dc-9f26-4254c8d5f964)

2023-08-05 16:48 UTC, SyedImtiyaz-1 commented
> > @narayan954 kindly review this.
> 
> will do, seeing some issues, like logo has no left padding/margin. Also login/signup page is looking bad on mobile view ![image](https://user-images.githubusercontent.com/77617189/258596108-845f81c1-b2fd-42dc-9f26-4254c8d5f964.png)

Okay, will add some media query to fix this issue.

2023-08-05 18:18 UTC, SyedImtiyaz-1 commented
@narayan954 Working on this give me some time.

2023-08-05 18:47 UTC, narayan954 commented
> @narayan954 Working on this give me some time.

take your time, I aint forcing anything

2023-08-05 19:14 UTC, SyedImtiyaz-1 commented
Hello @narayan954 ,
I have fixed the issue.
### Screenshot - 
![image](https://github.com/narayan954/dummygram/assets/121503426/7a515c70-1490-4290-bf0f-1b1add9efefc)

2023-08-06 00:38 UTC, narayan954 requested changes
![image](https://github.com/narayan954/dummygram/assets/77617189/38bcf42c-ac6f-4599-8a2c-a7f8d9f24eb5)
how did you check? you current changes are not reflected here

2023-08-06 06:03 UTC, SyedImtiyaz-1 commented
@narayan954 You can check now.
Previously there is a little issue happened with my internet but now its resolved and I have push the code properly.

2023-08-06 14:59 UTC, SyedImtiyaz-1 commented
@narayan954 ,
now ok ?

2023-08-06 20:28 UTC, narayan954 requested changes
login form is now misaligned as well. It's missing the bottom margin/padding compulsory for smooth look as earlier. 
- Logo is not aligned properly
- bottom space is lost(most screens)
- main app's css is getting affected/disturbed.
- too much space above(mobile)

Some of visual errors ss:
![image](https://github.com/narayan954/dummygram/assets/77617189/740f15f0-31a3-458c-b95b-7628eb6652e1)
original
![image](https://github.com/narayan954/dummygram/assets/77617189/ed36840e-a23d-4fa8-86fe-8d1aee01c9cc)

Changed Bottom
![image](https://github.com/narayan954/dummygram/assets/77617189/e12d7a21-9703-476e-952e-41071398480d)
original bottom
![image](https://github.com/narayan954/dummygram/assets/77617189/8db0fc84-38f5-49c0-8a5d-3898587898f7)

Changed home screen
![image](https://github.com/narayan954/dummygram/assets/77617189/03c9495e-b9bc-48f8-a014-6a3b767f9cbe)
Original home screen
![image](https://github.com/narayan954/dummygram/assets/77617189/ab269ad0-16b8-4e36-bd16-0090359ebd5e)


closing this pr, and updating the look in some seconds. See if you can update the issue according to the new look

2023-08-06 20:28 UTC, narayan954 commented on src/reusableComponents/Logo/index.jsx
> +      style={{ display:"flex", margin:".5vh auto", marginBottom:"2vh"}}
you're modifying a reusable component but still not checking the sideeffect

2023-08-06 20:28 UTC, narayan954 commented on src/reusableComponents/Logo/index.jsx
> +      style={{ display:"flex", margin:".5vh auto", marginBottom:"2vh"}}
nor handling the props

2023-08-06 20:28 UTC, narayan954 commented on src/reusableComponents/Logo/index.jsx
> +      style={{ display:"flex", margin:".5vh auto", marginBottom:"2vh"}}
in fact, the logo is still not in center of login form, and the logo is misbehaving in other parts of the website as well due to this

2023-08-06 20:33 UTC, closed without merging

2023-08-06 20:47 UTC, narayan954 commented
I am merging a new look of these pages, please work on that one if possible