Fix shimmer in dark mode and also add it on profile feed
narayan954/dummygram pull request #1156
Opened 2023-08-05 14:33 UTC by Palakkgoyal

This PR closes #1082 
I have fixed the shimmer effect on darkmode and also added in on the profile feed.

2023-08-05 19:46 UTC, narayan954 requested changes
Hi @Palakkgoyal there seems to be repetition of lots of code, if it seems feasible,can you try something like 
``` js
function FeedSkeleton() {
  const numSkeletons = 4;

  return (
    <>
      {Array.from({ length: numSkeletons }, (_, index) => (
        <Skeleton
          key={index}
          variant="rectangular"
          style={{
            width: "100%",
            height: "100%",
            aspectRatio: "1",
          }}
          className="shimmer_bg"
        />
      ))}
    </>
  );
}
```

2023-08-05 19:46 UTC, narayan954 commented on src/reusableComponents/PostSkeleton/index.jsx
> +        <Skeleton
again repetition of lots of code

2023-08-06 07:02 UTC, Palakkgoyal commented
Yes, sure. I will fix that.

2023-08-22 09:35 UTC, narayan954 approved these changes
looks good to me!

2023-08-22 09:35 UTC, merged