Validation added on Edit profile section
narayan954/dummygram pull request #1185
Opened 2023-08-07 04:24 UTC by Geeta259

issue #1147 
Empty validation check for each field.
Error message highlighted below of each field.

![Screenshot (67)](https://github.com/narayan954/dummygram/assets/75520947/faaa6562-3f2c-4a69-97c4-89e5ec8b5521)
![Screenshot (68)](https://github.com/narayan954/dummygram/assets/75520947/fbbf61b2-ce87-45b2-ad3d-449686bf629d)
![Screenshot (71)](https://github.com/narayan954/dummygram/assets/75520947/9a8bf017-1eb7-4907-a984-96ab4cc5c709)
![Screenshot (73)](https://github.com/narayan954/dummygram/assets/75520947/f498d9d2-5ebd-4c6f-b472-4fa821f1fa00)
![Screenshot (74)](https://github.com/narayan954/dummygram/assets/75520947/06661f8c-be86-463d-b2ea-4114eee7ce20)

@narayan954 Please look out this PR linked with issue #1147

2023-08-07 17:16 UTC, narayan954 requested changes
some minor changes

2023-08-07 17:16 UTC, narayan954 commented on src/components/EditProfile/index.jsx
> +  const [error, setError] = useState({});
define usestate in the top along with others to maintain consistency

2023-08-07 17:16 UTC, narayan954 commented on src/components/EditProfile/index.jsx
> +    console.log(editedData.name);
remove console logs as they're not required in production.... (though maybe I should add a plugin later to automatically remove them)

2023-08-07 17:17 UTC, narayan954 commented on src/components/EditProfile/index.jsx
> +    } else {
also, can we pick the above logic in a separate function to improve readibility?

2023-08-07 17:19 UTC, narayan954 commented
> issue #1147 Empty validation check for each field. Error message highlighted below of each field.
> 
> ![Screenshot (67)](https://user-images.githubusercontent.com/75520947/258699126-faaa6562-3f2c-4a69-97c4-89e5ec8b5521.png) ![Screenshot (68)](https://user-images.githubusercontent.com/75520947/258699130-fbbf61b2-ce87-45b2-ad3d-449686bf629d.png) ![Screenshot (71)](https://user-images.githubusercontent.com/75520947/258699135-9a8bf017-1eb7-4907-a984-96ab4cc5c709.png) ![Screenshot (73)](https://user-images.githubusercontent.com/75520947/258699140-f498d9d2-5ebd-4c6f-b472-4fa821f1fa00.png) ![Screenshot (74)](https://user-images.githubusercontent.com/75520947/258699143-06661f8c-be86-463d-b2ea-4114eee7ce20.png)
> 
> @narayan954 Please look out this PR linked with issue #1147

also, perhaps country and bio could be optional right?

2023-08-07 22:18 UTC, narayan954 commented
is it ready? Can you please resolve conflicts?

2023-08-08 04:07 UTC, Geeta259 commented
> @narayan954 Please look out this PR linked with issue #1147

check out this PR #1205

2023-08-08 04:16 UTC, narayan954 commented
> > @narayan954 Please look out this PR linked with issue #1147
> 
> check out this PR #1205

alright, closing this duplicate pr

2023-08-08 04:16 UTC, closed without merging