fix: caption hiding behind image issue
narayan954/dummygram pull request #1283
Opened 2023-10-20 00:42 UTC by 0xNunana

2023-10-20 05:54 UTC, narayan954 requested changes
kindly go through the comments. Minor changes requested

2023-10-20 05:54 UTC, narayan954 commented on src/components/ReadMore/index.jsx
> +    <div style={{zIndex:1,backgroundColor:'white',opacity:0.7}}>
please avoid inline styling as it reduces readability. You may add a class to this div with suitable name

2023-10-20 05:54 UTC, narayan954 commented on src/components/ReadMore/index.jsx
> +    <div style={{zIndex:1,backgroundColor:'white',opacity:0.7}}>
You may also want to check out the other occurrences of this component and see if they're mis-affected.

2023-10-21 18:18 UTC, narayan954 requested changes
please check where this component is used and fix the error.

2023-10-21 18:18 UTC, narayan954 commented on src/components/ReadMore/index.jsx
> +    <div className="caption_container">
please check the console, there's an error `<div> cannot appear as a descendant of <p>` perhaps due to this component being rendered inside a paragraph element.

2023-10-21 21:36 UTC, 0xNunana reviewed
changed the div into a span

2023-10-22 06:22 UTC, merged

2023-10-22 06:22 UTC, narayan954 commented
Thanks for your contribution! :)