updated new post modal
narayan954/dummygram pull request #196
Opened 2023-02-23 06:54 UTC by 1010varun

![Screenshot from 2023-02-22 15-22-39](https://user-images.githubusercontent.com/104075461/220837688-da7317ef-2c79-4e3e-b935-8c8c8477a6a2.png)

@narayan954, I have implemented a new post modal and I would appreciate it if you could review my pull request and merge it.
I understand that you had previously mentioned creating a new branch for new issues, but I have already made these changes and cannot create a new branch at the moment. However, I will make sure to create a new branch for future issues.

Thank you.

2023-02-23 15:37 UTC, narayan954 requested changes
I have marked some errors, please resolve them. Also, try to style the modal like picture you've provided.
![new post modal](https://user-images.githubusercontent.com/77617189/220955394-b31afb2e-d723-4345-a48d-56c013c6408a.png)

2023-02-23 15:37 UTC, narayan954 commented on src/App.jsx
> +      <Dialog style={{borderRadius: "100px"}} open={openNewUpload} onClose={() => setOpenNewUpload(false)}>
using reserved prop-names like className and style(in this case) on custom components hurts readability and makes the code harder to maintain. These props should only be used for DOM nodes like div, a, span, etc.
You can take a look into this [mui.com/material-ui/customization/how-to-customize](https://mui.com/material-ui/customization/how-to-customize/) and fix it.

2023-02-23 15:37 UTC, narayan954 commented on src/App.jsx
> +        <center><img
don't use deprecated tags like centered and update it with modern css alignment approach. You might refer to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

2023-02-23 18:44 UTC, narayan954 requested changes
still, center tag exists, please fix it

2023-02-24 07:28 UTC, 1010varun commented
@narayan954, I have removed all the center tags.

Kindly review and merge my pr.

2023-02-24 17:48 UTC, narayan954 requested changes
this workaround of center tag isn't responsive for other screens. You can check the mobile view for reference
![mobile-view](https://user-images.githubusercontent.com/77617189/221251817-eed734a0-513d-42be-9486-c6af8cbe5255.png)

using marginleft property won't make the elements centered and responsive here. You can use flexbox/grid to center the elements

2023-02-24 17:59 UTC, 1010varun commented
![image](https://user-images.githubusercontent.com/104075461/221254663-29ed62f2-568d-4cb3-9336-eda29ca6a256.png)
 
@narayan954 is this perfect

2023-02-24 18:10 UTC, narayan954 commented
> ![image](https://user-images.githubusercontent.com/104075461/221254663-29ed62f2-568d-4cb3-9336-eda29ca6a256.png)
> 
> ![image](https://user-images.githubusercontent.com/104075461/221254867-a7143b2d-1bf8-4128-bd5f-4b2412a8cbd5.png)
> 
>  
> @narayan954 is this perfect

No, nothing is perfect, but in this case I'm suggesting you not to disturb the current alignment of other components as it looks in the screenshot below.
[]()![Screenshot_2023-02-24-23-38-42-066_com.android.chrome.jpg](https://user-images.githubusercontent.com/77617189/221256617-1dec146d-f78c-414e-bd92-09fe7fa79ae0.jpg)

2023-02-24 18:23 UTC, 1010varun commented
![image](https://user-images.githubusercontent.com/104075461/221259435-de7c4b82-2d6b-4c74-9a72-d9b6e634b0e1.png)


@narayan954 now is this correct

2023-02-24 18:35 UTC, 1010varun commented
@narayan954 now please review and merge my pr.

2023-02-24 19:10 UTC, narayan954 approved these changes
looks good to me!

2023-02-24 19:12 UTC, merged

2023-02-24 19:13 UTC, narayan954 commented
thanks for your contribution