Added functionality to add post without uploading an image
narayan954/dummygram pull request #27
Opened 2022-10-01 20:17 UTC by partik03

This pr is in response to the issue #25 by @mathiasayivor

2022-10-01 21:22 UTC, narayan954 commented
Can you please resolve the conflicts @partik03

2022-10-02 06:54 UTC, partik03 commented
@narayan954 I have resolved the conflicts kindly merge it

2022-10-02 07:00 UTC, narayan954 requested changes
please check my comment on the code

2022-10-02 07:19 UTC, narayan954 commented on src/components/ImgUpload.jsx
> -    setUploadingPost(true);
alright I am doing it myself :) , so it won't be delayed

2022-10-02 07:21 UTC, narayan954 approved these changes
looks good :)

2022-10-02 07:21 UTC, merged