Update Post Caption
narayan954/dummygram pull request #287
Opened 2023-05-21 19:04 UTC by abhishek3434

**Solved-Update feature for Posts #151**
- Added a dialog box from MaterialUI to edit post caption

![Screenshot from 2023-05-21 03-15-41](https://github.com/narayan954/dummygram/assets/38461721/481b5207-07b1-430f-ad46-4931ca161666)
![Screenshot from 2023-05-21 03-15-52](https://github.com/narayan954/dummygram/assets/38461721/9c87c5c3-e310-4322-beb7-27cdb42e3656)
![Screenshot from 2023-05-21 03-15-02](https://github.com/narayan954/dummygram/assets/38461721/a3c25977-6c97-4735-af56-7e0b8e22e1d6)

2023-05-22 23:14 UTC, narayan954 requested changes
please apply code formatting and remove unnecessary elements as asked

2023-05-22 23:14 UTC, narayan954 commented on src/components/Post.jsx
> +  const[editCaption,setEditCaption]=useState(caption)
please maintain a proper format, try using auto formatter like prettier to format the code :)

2023-05-22 23:14 UTC, narayan954 commented on src/components/Post.jsx
> +  const [openEditCaption,setOpenEditCaption]=useState(false);
again formatting improper

2023-05-22 23:14 UTC, narayan954 commented on src/components/Post.jsx
> +
extra line, lots of formatting issues. format the whole code please using a formatter

2023-05-22 23:14 UTC, narayan954 commented on src/components/Post.jsx
> +    let data= await db.collection("posts").doc(postId).get().then(doc =>{
was this query even needed??

2023-05-23 19:42 UTC, abhishek3434 commented
> please apply code formatting and remove unnecessary elements as asked

Completed please check now

2023-05-23 19:52 UTC, abhishek3434 commented on src/components/Post.jsx
> +    let data= await db.collection("posts").doc(postId).get().then(doc =>{
No need of this query removed noq

2023-05-23 22:13 UTC, narayan954 commented on src/components/Post.jsx
> +import { useEffect, useState } from "react";
why is there duplicate import of modules? please fix that and test if the application runs without issue.

2023-05-23 23:31 UTC, narayan954 commented
Also, please try to solve the merge conflict

2023-05-24 20:24 UTC, closed without merging