Overflow of Caption fixed with added new class and by defining it in …
narayan954/dummygram pull request #291
Opened 2023-05-22 09:07 UTC by Shubham185y

…css file as well

2023-05-22 23:05 UTC, narayan954 requested changes

2023-05-22 23:05 UTC, narayan954 commented on src/components/Post.jsx
> -          <div className="post__background">{caption}</div>
it's not an addition if you're replacing the class. We still need the background from post__background class. You may add both classes and verify if it still works

2023-05-22 23:05 UTC, narayan954 commented on src/components/Post.jsx
> -                        <div className="post__background">{caption}</div>
same as earlier comment

2023-05-22 23:05 UTC, narayan954 commented on src/index.css
> +  width: 384px;
try not to hardcode in pixels, use responsive measurement units like em, rem

2023-05-23 08:26 UTC, Shubham185y commented
![image](https://github.com/narayan954/dummygram/assets/100077254/a080fe06-483b-4f04-8571-d2f37d76ddf7)
responsive as well:
![image](https://github.com/narayan954/dummygram/assets/100077254/4e9abb2c-dfb4-4fc9-b329-133a5bd10f2c)

2023-05-23 09:00 UTC, narayan954 approved these changes
looks good to me!

2023-05-23 09:02 UTC, merged

2023-05-23 09:02 UTC, narayan954 commented
Thanks for your contribution :)