changed input element properties
narayan954/dummygram pull request #315
Opened 2023-05-23 14:53 UTC by raghav1030

changed the mouse pointer behavior when hovered and focused on input elements in login form.

2023-05-23 21:31 UTC, narayan954 requested changes
needs some minor changes

2023-05-23 21:31 UTC, narayan954 commented on src/pages/Login.jsx
> +import './Login.css'
if it's a common css for both file, you may name it index.css or style.css.

2023-05-23 21:31 UTC, narayan954 commented on src/pages/Login.jsx
> +
format the code as well

2023-05-23 21:32 UTC, narayan954 commented
mention the issue number you're solving as well in the pr so it can be linked

2023-05-26 16:14 UTC, narayan954 commented
@raghav1030  are you attending this issue?

2023-05-27 14:20 UTC, raghav1030 commented
Yes I'll be making changes  into it.

Actually my end sems were going on so I was a bit inactive here.

2023-05-27 21:29 UTC, narayan954 commented
> Yes I'll be making changes into it.
> 
> Actually my end sems were going on so I was a bit inactive here.

ohhh alright then

2023-05-27 21:44 UTC, narayan954 approved these changes
looks good to me!

2023-05-27 21:44 UTC, merged

2023-05-27 22:07 UTC, narayan954 commented
Thanks for your contribution! :)