Home Page navigation fixed issue #316
narayan954/dummygram pull request #335
Opened 2023-05-24 14:54 UTC by Lakshyyaa

fixed issue #316

2023-05-24 20:32 UTC, narayan954 requested changes
need to fix that

2023-05-25 07:08 UTC, Lakshyyaa commented on src/App.jsx
> +            else{
yes, here if user's on login/signup and clicks on the logo he/she will be redirected to the same page.
But, if you wish for no navigation action to be performed when user is on login/signup. I have the code ready 
waiting for your merge approval

2023-05-25 07:48 UTC, Lakshyyaa commented on src/App.jsx
> +            else{
hey i made a new commit solve it

2023-05-25 20:18 UTC, narayan954 commented on src/App.jsx
> +            else{
great, mergin

2023-05-25 20:21 UTC, narayan954 approved these changes
looks good to me for now, but actually this implementation is incomplete and hard-coded. Need to fix it with a better approach later

2023-05-25 20:21 UTC, merged