#367-added close button on new posts
narayan954/dummygram pull request #368
Opened 2023-05-27 18:28 UTC by Soulpurr

fixes #367 
So i have added a cross on create new posts which closes the current window
[scrnli_27_05_2023_23-53-33.webm](https://github.com/narayan954/dummygram/assets/92094765/999b332c-447a-4e6f-b849-e75f144661e0)

2023-05-27 18:30 UTC, Soulpurr commented
@narayansoni pls approve this pr

2023-05-27 22:01 UTC, narayan954 requested changes
minor changes

2023-05-27 22:01 UTC, narayan954 commented on src/components/ImgUpload.jsx
> +import {AiOutlineClose} from 'react-icons/ai'
extra import

2023-05-27 22:01 UTC, narayan954 commented on src/components/ImgUpload.jsx
> +  const [close, setclose] = useState(false)
unnecessary state

2023-05-28 01:58 UTC, Soulpurr commented on src/components/ImgUpload.jsx
> +  const [close, setclose] = useState(false)
Ohh just missed will fix it

2023-05-28 03:57 UTC, Soulpurr commented
@narayan954  can you pls verify that the changes are reflected or not

2023-05-28 13:51 UTC, narayan954 commented
> @narayan954 can you pls verify that the changes are reflected or not

yes all right!

2023-05-28 13:52 UTC, Soulpurr commented
Pls approve it then🥹

2023-05-28 13:53 UTC, narayan954 commented
> Pls approve it then🥹

there you go!

2023-05-28 13:53 UTC, narayan954 approved these changes
looks good to me!

2023-05-28 13:53 UTC, merged

2023-05-28 13:54 UTC, narayan954 commented
Thanks for your contribution!