Text Entered by User Should be Line breaked as it is he entered
narayan954/dummygram pull request #382
Opened 2023-05-28 22:32 UTC by Gurmeet-Singh657

Resolved Issue-Number-348
Text Entered by User will be sent as it is to backend and fetched by preserving Line Breaks
Please merge my pull request

![image](https://github.com/narayan954/dummygram/assets/83361657/896387d6-ce55-428b-ade4-619f2b1ac39c)

2023-05-29 09:28 UTC, narayan954 requested changes
Hi @Gurmeet-Singh657 are you sure your pr is in sync with this repo, as I can see a lots of feature are being overwritten in this pull request, Please fix that

2023-05-29 13:58 UTC, Gurmeet-Singh657 commented
I have Resolved the Changes. Please merge my Pull Request !!

2023-05-29 15:12 UTC, narayan954 requested changes
Kindly doubleCheck your changes, why are you removing so many features which are already present in the application

2023-05-29 15:39 UTC, Gurmeet-Singh657 commented
@narayan954 If possible can you plz help me in resolving this !! Because I think there is some inconsistency in my forked repo

2023-05-29 16:24 UTC, narayan954 commented
> @narayan954 If possible can you plz help me in resolving this !! Because I think there is some inconsistency in my forked repo

You may force update your fork with my master branch

2023-06-08 10:47 UTC, narayan954 requested changes
minor change requested

2023-06-08 10:47 UTC, narayan954 commented on src/components/Post.jsx
> +                <p style={{ whiteSpace: 'pre-line' }} className="post_caption">{caption}</p>
instead of adding inline styles, can we put these styles where they belong in index.css?

2023-06-08 11:43 UTC, narayan954 approved these changes
lgtm!

2023-06-08 11:44 UTC, merged