Fix home layout that was messing up with sidebar
narayan954/dummygram pull request #467
Opened 2023-06-13 09:40 UTC by Palakkgoyal

This PR fixes issue no. #460 

https://github.com/narayan954/dummygram/assets/116902573/37e6ee3f-f428-4626-a57b-b01aac958481

2023-06-14 21:11 UTC, narayan954 requested changes
looks good to me, just a little correction needed

2023-06-14 21:11 UTC, narayan954 commented on src/index.css
> +  padding-left: 17vw;
these could've turned to one liner

2023-06-14 21:15 UTC, narayan954 approved these changes
lgtm!

2023-06-14 21:15 UTC, merged

2023-06-15 04:43 UTC, Palakkgoyal commented
What corrections do you want to have? I will add them for sure.

2023-06-16 22:16 UTC, narayan954 commented
> What corrections do you want to have? I will add them for sure.

I corrected them myself, in my [commit](https://github.com/narayan954/dummygram/pull/467/commits/a0c0ed28af0b8d1ab7589d296dcd81f26dbf0eb7) , you may read the resolved conversation to know more