New Post UI Responsive + New Component Created for New Post
narayan954/dummygram pull request #488
Opened 2023-06-16 19:35 UTC by Gurmeet-Singh657

Issue Number 476

New Post UI was made Responsive for Mobiles as well. Here it looks like
![image](https://github.com/narayan954/dummygram/assets/83361657/222b928b-233a-4a3f-9377-4e48fe9d385d)

After Adding the post, looks like
![image](https://github.com/narayan954/dummygram/assets/83361657/802884d3-568e-4128-be2e-c3359fc6d4a9)

And Also, the New Post component is created separately.
Please merge my pull request as a GSSOC'23 Contributor.

2023-06-16 23:46 UTC, narayan954 commented
Hi @Gurmeet-Singh657 , this vertical view would look good in mobile devices and current view is better for desktops actually, I think, what do you say? I'm yet to look into this pr. Do you think you can handle these separate view for desktop and mobiles?

2023-06-17 10:08 UTC, narayan954 commented
Can you please look into this?? 
![image](https://github.com/narayan954/dummygram/assets/77617189/c3bae6ac-abcb-4084-a13c-a701bb1ee3e1)

2023-06-17 10:12 UTC, narayan954 requested changes
mobile screens are not responsive, yet

2023-06-17 10:12 UTC, narayan954 commented on src/components/NewPost.jsx
> +    console.log("I am Happy Today");
no console logs in production

2023-06-17 10:12 UTC, narayan954 commented on src/components/NewPost.jsx
> +  console.log("I am Happy Today");
no console logs in production

2023-06-17 10:12 UTC, narayan954 commented
> Issue Number 476
> 
> New Post UI was made Responsive for Mobiles as well. Here it looks like ![image](https://user-images.githubusercontent.com/83361657/246515703-222b928b-233a-4a3f-9377-4e48fe9d385d.png)
> 
> After Adding the post, looks like ![image](https://user-images.githubusercontent.com/83361657/246515934-802884d3-568e-4128-be2e-c3359fc6d4a9.png)
> 
> And Also, the New Post component is created separately. Please merge my pull request as a GSSOC'23 Contributor.

this is tablet view/screen

2023-06-17 10:29 UTC, Gurmeet-Singh657 commented
Ohk, I will fix it 🙂

2023-06-27 08:32 UTC, narayan954 commented
closing this, you can open another pr

2023-06-27 08:33 UTC, closed without merging