Add profile views counter
narayan954/dummygram pull request #561
Opened 2023-06-24 17:44 UTC by Palakkgoyal

This PR closes issue no. #543 
Implemented a profile view counter and it does not update on every render rather I have used session storage to check if the views are updated and if not then, update the views only once in a particular session.

2023-06-25 21:35 UTC, narayan954 requested changes
check the comment, will look into this again today

2023-06-25 21:35 UTC, narayan954 commented on src/reusableComponents/ViewsCounter.jsx
> +          .where("uid", "==", auth.currentUser.uid)
won't this just update the user's view of his own profile only?

2023-06-26 06:47 UTC, Palakkgoyal commented
Let me go through it once again.

2023-06-26 07:22 UTC, Palakkgoyal commented
Yes, you are right. I think we should use username for all these checkings.

2023-06-26 15:19 UTC, narayan954 commented
> Yes, you are right. I think we should use username for all these checkings.

yes, it seems it's not that simple.

2023-06-26 16:16 UTC, Palakkgoyal commented
Yes, I initially thought it would be easy to implement. But, no worries, I will give my best.

2023-06-27 07:00 UTC, narayan954 commented
> Yes, I initially thought it would be easy to implement. But, no worries, I will give my best.

Best of luck! :)

2023-06-29 12:45 UTC, narayan954 commented
is this done?

2023-06-29 14:30 UTC, Palakkgoyal commented
Not yet, I thought it would be better if I use username instead of display name. So, for sometime I stopped working on this.

2023-06-29 18:11 UTC, narayan954 commented
> Not yet, I thought it would be better if I use username instead of display name. So, for sometime I stopped working on this.

Ohh alright! you did right!

2023-07-12 11:52 UTC, closed without merging