Implemented dark mode
narayan954/dummygram pull request #594
Opened 2023-06-30 08:43 UTC by Palakkgoyal

This PR closes issue no. #541 
![Screenshot 2023-06-30 133147](https://github.com/narayan954/dummygram/assets/116902573/f0a4c49a-7812-425c-819a-02af95a03253)
![Screenshot 2023-06-30 133228](https://github.com/narayan954/dummygram/assets/116902573/6ae38586-63b6-4cce-8c75-cad5eb3d50d1)
![Screenshot 2023-06-30 133303](https://github.com/narayan954/dummygram/assets/116902573/08db93b4-06c5-47f0-9734-b73e2e3410b2)
![Screenshot 2023-06-30 133322](https://github.com/narayan954/dummygram/assets/116902573/fd3c54f9-3bcf-4a01-9b4f-df9e2a1e362a)

2023-06-30 09:54 UTC, narayan954 requested changes
You did really good, but some of the styles are missing such as the shadow effects on logout modal
![image](https://github.com/narayan954/dummygram/assets/77617189/8b52da73-6b01-4625-83c6-0846d5588125)
Signup and signin pages have also lost their cover
![image](https://github.com/narayan954/dummygram/assets/77617189/be77a2b5-bf2c-438d-b461-af5a1460c49c)

Also, I've applied background color from github dark mode
![image](https://github.com/narayan954/dummygram/assets/77617189/9e6a4138-31b8-4081-9e33-907d28884452)
Is that okay??
Please fix those lost styles and I can update the difficulty level of this issue :)

2023-06-30 09:54 UTC, narayan954 commented on index.html
> +      <script src="/src/js/darkMode.js" type="module"></script>
this file doesn't exists

2023-06-30 10:01 UTC, Palakkgoyal commented
Yes, sure. I will do the required changes.

2023-06-30 10:38 UTC, Palakkgoyal commented
Did all the changes. Please review the
![Screenshot (565)](https://github.com/narayan954/dummygram/assets/116902573/b54cd0bc-6a3d-4243-b290-d459388fecdd)
![Screenshot (566)](https://github.com/narayan954/dummygram/assets/116902573/6706f5ee-c251-42eb-b183-4838628c0b57)
![Screenshot (567)](https://github.com/narayan954/dummygram/assets/116902573/36d5a80a-8fd7-4501-9700-50e6e3d5821a)
m.

2023-06-30 12:26 UTC, narayan954 approved these changes
looks good to me!

2023-06-30 12:27 UTC, merged

2023-07-08 14:21 UTC, narayan954 commented
> 
> @narayan954 Dont give level3 tags to such basic work. it is atmost level2

it's level 2 only, might've assigned level2 by mistake