Optimize favorites page fetch requests
narayan954/dummygram pull request #619
Opened 2023-07-02 16:51 UTC by Palakkgoyal

This PR closes issue no. #607 
You can check the optimization by:
- remove all posts from favorites then, reload the favorite page, it will take no time for the optimized version to load but, very much for the unoptimized one.
- try the same thing by adding some posts to favorites, optimized version will take less time than the other one.

2023-07-02 20:56 UTC, narayan954 requested changes
favourite page is giving error, can you try fixing that?
`Uncaught TypeError: Cannot destructure property 'caption' of 'post' as it is undefined`

2023-07-02 20:56 UTC, narayan954 commented on src/components/Favorite.jsx
> +  const savedPostsArr = JSON.parse(localStorage.getItem("posts"));
this won't always exist, right? add a default value

2023-07-03 07:01 UTC, Palakkgoyal commented
Okay. Going to fix these bugs.

2023-07-03 07:48 UTC, Palakkgoyal commented
> favourite page is giving error, can you try fixing that? `Uncaught TypeError: Cannot destructure property 'caption' of 'post' as it is undefined`
Hey @narayan954 I fixed the console.log and also given a default value to the savedPostsArr but, I am not getting any error as you said related to caption.

2023-07-03 19:47 UTC, narayan954 commented
> > favourite page is giving error, can you try fixing that? `Uncaught TypeError: Cannot destructure property 'caption' of 'post' as it is undefined`

>  Hey @narayan954 I fixed the console.log and also given a default value to the savedPostsArr but, I am not getting any error as you said related to caption.

reviewing :)

2023-07-03 19:54 UTC, narayan954 commented
> > favourite page is giving error, can you try fixing that? `Uncaught TypeError: Cannot destructure property 'caption' of 'post' as it is undefined`
> 
> Hey @narayan954 I fixed the console.log and also given a default value to the savedPostsArr but, I am not getting any error as you said related to caption.

see :/
![image](https://github.com/narayan954/dummygram/assets/77617189/a506d1d4-bd7f-4bdc-ae77-61a35342e22f)

2023-07-03 20:19 UTC, narayan954 commented
> > > favourite page is giving error, can you try fixing that? `Uncaught TypeError: Cannot destructure property 'caption' of 'post' as it is undefined`
> > 
> > 
> > Hey @narayan954 I fixed the console.log and also given a default value to the savedPostsArr but, I am not getting any error as you said related to caption.
> 
> see :/ ![image](https://user-images.githubusercontent.com/77617189/250650467-a506d1d4-bd7f-4bdc-ae77-61a35342e22f.png)

some posts are undefined, maybe that's because they're deleted?
![image](https://github.com/narayan954/dummygram/assets/77617189/1913728d-45f0-4a92-853a-49b4971541b2)

2023-07-03 20:29 UTC, narayan954 approved these changes
looks good to me!

2023-07-03 20:29 UTC, merged

2023-07-04 06:45 UTC, Palakkgoyal commented
Okay, got that its very necessary to check every aspect of code.

2023-07-04 08:30 UTC, narayan954 commented
> Okay, got that its very necessary to check every aspect of code.

yes! :)