Profile page UI
narayan954/dummygram pull request #639
Opened 2023-07-03 19:17 UTC by anamika7153

### Closes: #601 

|   Before  |   Updated                |
|-----|---------------------------------|
| <img width="460" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/53eebbb2-65eb-4196-8d8d-d8ac5048a8d3"> | <img width="460" src="https://github.com/narayan954/dummygram/assets/66116440/e0d787a5-9e96-4e35-b89f-b8da33a1482f"> |
| <img width="460" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/97266eec-e8b0-4413-a124-5ba37820155a"> | <img width="460" src="https://github.com/narayan954/dummygram/assets/66116440/45ce4dbc-8b2c-4590-9d13-45525f95fbfd"> |
| <img width="460" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/b93d50fa-00bc-4e59-9c7e-cb0d9ac0a204"> | <img width="460" src="https://github.com/narayan954/dummygram/assets/66116440/e0fac64d-5d24-464c-8d67-807ec0b669d8"> |

2023-07-03 23:15 UTC, narayan954 requested changes
can we please reduce/optimise media queries?
also, the back button is lagging as you can see
![image](https://github.com/narayan954/dummygram/assets/77617189/b9800ded-8c03-4fd4-bbc5-26c3e9d48312)

Also mobile display is like this now
![image](https://github.com/narayan954/dummygram/assets/77617189/3e5e8e7b-9a8a-49f6-9527-1f532e7f7fef)

2023-07-03 23:15 UTC, narayan954 commented on src/pages/Profile/index.css
> +@media screen and (max-width: 800px) {
why are there too many media queries for even similar sizes?

2023-07-04 17:49 UTC, anamika7153 commented
@narayan954 I'm on it.

2023-07-04 20:09 UTC, narayan954 commented
> @narayan954 I'm on it.

best of luck!

2023-07-04 20:11 UTC, narayan954 commented
Also, maybe we dont need that back button here, as other options are available directly in the sidebar. You may remove that

2023-07-04 20:13 UTC, anamika7153 commented
> Also, maybe we dont need that back button here, as other options are available directly in the sidebar. You may remove that

Noted

2023-07-12 19:21 UTC, anamika7153 commented
### Screenshots

| | |
|---|-----|
|<img width="497" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/2073d753-3392-42c7-9b24-13aa0b892546"> | <img width="496" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/a551058a-5fdc-4087-b7ee-0c0490544374"> |
| <img width="497" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/6f518f3f-3d13-498e-a40e-83a4a263df4d"> |<img width="495" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/27a28745-58fd-4ecb-aa6e-70c8f63da2b3"> |

2023-07-12 23:07 UTC, narayan954 approved these changes
looks good to me!

2023-07-12 23:08 UTC, narayan954 commented
It looks good to me!

2023-07-12 23:09 UTC, merged