Improved Post UI
narayan954/dummygram pull request #643
Opened 2023-07-04 07:48 UTC by Tisha6661

The post Ui is made UI , More responsive , optimized css.

##Issue Number- 
#628

2023-07-04 19:25 UTC, Tisha6661 commented
@narayan954 Is there any issue?

2023-07-04 19:38 UTC, narayan954 requested changes
Minor changes requested

![image](https://github.com/narayan954/dummygram/assets/77617189/67ec143a-b5bf-498e-8a57-8ba5fd0e542e)
can you please adjust the color of send button and `No comments` as well?

2023-07-04 19:38 UTC, narayan954 commented on src/reusableComponents/ImageSlider/index.jsx
> +              height: "100%",
Hi @Tisha6661 giving variable height will cause issue to grid view of posts as you can see in photo
![image](https://github.com/narayan954/dummygram/assets/77617189/fb4f91a2-8be7-4f8c-9a9f-9307543b631e)
you may either rollback or add different style/fix height of posts in grid view.
There's another option as well, they can showed as canvas as well of variable heights

2023-07-04 19:38 UTC, narayan954 commented on src/components/Post/index.css
> +.p-0 {
give this class a more defining name to what it does, like `no-padding` or `padding-0`

2023-07-04 19:39 UTC, narayan954 commented
> @narayan954 Is there any issue?

its fine, just minor changes

2023-07-04 21:21 UTC, narayan954 commented
> Minor changes requested
> 
> ![image](https://user-images.githubusercontent.com/77617189/250980008-67ec143a-b5bf-498e-8a57-8ba5fd0e542e.png) can you please adjust the color of send button and `No comments` as well?

you may skip fixing the color of send button and `No comments` if you want. Someone else might work on that

2023-07-05 05:59 UTC, Tisha6661 commented
No issues I have done that! Just fixing the height.

2023-07-05 06:58 UTC, Tisha6661 commented
I have changed the comment box, but now there is some issue with the site, I am unable to make changes-
![image](https://github.com/narayan954/dummygram/assets/98682478/b3017979-093c-41fb-8232-de18e151231f)

2023-07-05 08:45 UTC, narayan954 commented
> No issues I have done that! Just fixing the height.

I was reviewing this, height issue is yet to be fixed.

2023-07-05 08:47 UTC, narayan954 requested changes
height issue left

2023-07-05 15:53 UTC, Tisha6661 commented
@narayan954 I've checked several times, but the quota exceeded is showing everytime.

2023-07-05 17:53 UTC, narayan954 commented
> @narayan954 I've checked several times, but the quota exceeded is showing everytime.

oh ok then, contact me, I'll be generating some credentials for testing... you can/may also follow the steps in readme to generate your own credentials

2023-07-05 17:58 UTC, narayan954 commented
https://github.com/narayan954/dummygram/blob/master/DATABASEconf.md

2023-07-07 17:05 UTC, narayan954 commented
Hi @Tisha6661 are you working on this?

2023-07-07 17:08 UTC, Tisha6661 commented
@narayan954 I tried working through firebase, but it was my first time, so i couldn't work on it. I was waiting for the site to work.

2023-07-07 17:10 UTC, Tisha6661 commented
@narayan954 If it's working, I'll work right away.

2023-07-07 17:16 UTC, narayan954 commented
> @narayan954 I tried working through firebase, but it was my first time, so i couldn't work on it. I was waiting for the site to work.

You should've asked for help, you just needed to change credentials in the .env file in our project and project would've started working full fledged. To generate the credentials , follow the guide link I sent earlier. Else, message me, I'll share you direct credentials for testing.Also, I'll get the website working soon as I'll be getting some time now.

2023-07-07 17:20 UTC, Tisha6661 commented
@narayan954 Sure thing, I try again on firebase with this information today only, if not I'll wait for site to be working, and will finish the work that very day.

2023-07-07 17:33 UTC, narayan954 commented
> @narayan954 Sure thing, I'll try again on firebase with this information today only, if not I'll wait for site to be working, and will finish the work that very day.

alright, that works!

2023-07-08 20:14 UTC, narayan954 commented
> @narayan954 Sure thing, I'll try again on firebase with this information today only, if not I'll wait for site to be working, and will finish the work that very day.

website should be working now, fetch the latest changes

2023-07-09 09:24 UTC, Tisha6661 commented
@narayan954 I have fixed the card-

![image](https://github.com/narayan954/dummygram/assets/98682478/9dd9f4b9-c0b0-497f-bb42-2e81c83ae4f4)

2023-07-09 17:56 UTC, narayan954 commented
> @narayan954 I have fixed the card-
> 
> ![image](https://user-images.githubusercontent.com/98682478/252136817-9dd9f4b9-c0b0-497f-bb42-2e81c83ae4f4.png)

it's still having the height error as I mentioned
![image](https://github.com/narayan954/dummygram/assets/77617189/91acb408-a766-4fbf-a0b6-166b59f036cc)

2023-07-09 17:59 UTC, Tisha6661 commented
@narayan954 but for this we have to put a constraint that the image can't take more space that a particular space, let me just work on it, will show you the results today only.

2023-07-09 18:07 UTC, narayan954 requested changes
please fix the height of post and let some margin persist in post header.

2023-07-09 18:07 UTC, narayan954 commented
> @narayan954 but for this we have to put a constraint that the image can't take more space that a particular space, let me just work on it, will show you the results today only.

oh alright

2023-07-09 18:08 UTC, narayan954 commented
> @narayan954 but for this we have to put a constraint that the image can't take more space that a particular space, let me just work on it, will show you the results today only.

yes, else, we would have to adjust the post grid to be like a canvas

2023-07-09 18:09 UTC, Tisha6661 commented
@narayan954 Sure, I'll try to allow the image fitting like on original instagram.

2023-07-09 18:11 UTC, narayan954 commented on src/components/Post/ImgBox.jsx
> +              {caption}
caption is repeating, please fix that as well

2023-07-09 19:37 UTC, Tisha6661 commented
@narayan954 Made the changes, please review-

![image](https://github.com/narayan954/dummygram/assets/98682478/b602cc3c-4afb-4e0a-bcd8-69552d7e2cda)
![image](https://github.com/narayan954/dummygram/assets/98682478/02c5a1d8-4e38-4096-a4a7-194ac6eacaeb)

2023-07-09 20:23 UTC, narayan954 requested changes
Hi Tisha, responsiveness is breaking critically for mobile devices, can you please check that? rest everything seems fine.

Thank you.
I hope this is the last time I bug you on this issue XD

2023-07-09 20:24 UTC, narayan954 commented
![image](https://github.com/narayan954/dummygram/assets/77617189/a55447ce-a5ba-4bf1-9dbe-57c6d355c541)
![image](https://github.com/narayan954/dummygram/assets/77617189/26aa08c4-2af5-4898-b377-a7fd61980275)

see :/

2023-07-09 20:34 UTC, Tisha6661 commented
@narayan954 Long captions will again make the pages uneven, because in grid mode if we'll add long caption like this, which is uncertain in all posts, some will write small caption, and some no caption at all. So it would never would in grid view or make the cards even. See-

![image](https://github.com/narayan954/dummygram/assets/98682478/9533c6ac-5ba2-46a1-bbb3-e7116cbb47eb)

2023-07-10 20:48 UTC, narayan954 commented
> @narayan954 Long captions will again make the pages uneven, because in grid mode if we'll add long caption like this, which is uncertain in all posts, some will write small caption, and some no caption at all. So it would never would in grid view or make the cards even. See-
> 
> ![image](https://user-images.githubusercontent.com/98682478/252167843-9533c6ac-5ba2-46a1-bbb3-e7116cbb47eb.png)
> 
> Unless we put an overflow auto.

you're correct, I think either we can have a min height prop or the overflow control.... but there also please give it height enough to not look bad, as earlier it was just one line with scroll option. Sorry for delaying the pr

2023-07-12 18:30 UTC, Tisha6661 commented
@narayan954 I have made the changes, here-

https://github.com/narayan954/dummygram/assets/98682478/fad71771-f0a5-439a-b9df-5399aa16be74

2023-07-12 23:11 UTC, narayan954 commented
> @narayan954 I have made the changes, here-
> 
>  dummy.mp4

reviewing!

2023-07-13 00:03 UTC, narayan954 approved these changes
looks good to me!

2023-07-13 00:03 UTC, merged

2023-07-13 00:04 UTC, narayan954 commented
Thanks for your contribution!