added cancel button
narayan954/dummygram pull request #790
Opened 2023-07-13 17:38 UTC by anamika7153

Closes: #756 

### Video

https://github.com/narayan954/dummygram/assets/66116440/ef642e16-c73d-4bee-9da4-c93f22edc17d

2023-07-13 21:02 UTC, narayan954 requested changes
some minor changes requested. Also a doubt, are you replacing visible with profilepic?

2023-07-13 21:02 UTC, narayan954 commented on src/pages/Profile/index.jsx
> +    setProfilePic(null);
again same doubt

2023-07-13 21:13 UTC, anamika7153 commented
> some minor changes requested. Also a doubt, are you replacing visible with profilepic?

Yeah, when I added the cancel btn and cancel function visible state wasn't changing from true to false even after updating the state. Issue might be with the order of state updates. I couldn't solve it. udating the profilepic worked. So I tested it and used it.

2023-07-13 21:15 UTC, anamika7153 commented on src/pages/Profile/index.jsx
> +    setProfilePic(null);
> should we set it to null or the actual avatar?

I needed to render the buttons conditionally. That is why I set it to null. Also, Setting it to null wasn't creating any issues with the original avatar.

2023-07-13 21:30 UTC, narayan954 commented
> > some minor changes requested. Also a doubt, are you replacing visible with profilepic?
> 
> Yeah, when I added the cancel btn and cancel function visible state wasn't changing from true to false even after updating the state. Issue might be with the order of state updates. I couldn't solve it. udating the profilepic worked. So I tested it and used it.

let's merge the pic updating issue first as it can cause conflicts

2023-07-13 21:34 UTC, anamika7153 commented
> > > some minor changes requested. Also a doubt, are you replacing visible with profilepic?
> > 
> > 
> > Yeah, when I added the cancel btn and cancel function visible state wasn't changing from true to false even after updating the state. Issue might be with the order of state updates. I couldn't solve it. udating the profilepic worked. So I tested it and used it.
> 
> let's merge the pr for pic updating issue first as it can cause conflicts with this pr. I've commented there

Okay, I'll notify when I'm done with that.

2023-07-14 23:51 UTC, narayan954 commented on src/pages/Profile/index.jsx
> +    setProfilePic(null);
Ohh, I think variable names are creating confusions, that's why I had this doubt

2023-07-24 16:26 UTC, narayan954 commented
closing as duplicate to #926

2023-07-24 16:26 UTC, closed without merging