theam button fix #647
narayan954/dummygram pull request #857
Opened 2023-07-17 19:09 UTC by biplavmz

bug issue #647 Theam button position change and icon change.
<img width="113" alt="image" src="https://github.com/narayan954/dummygram/assets/68702055/33c2ac0f-ff43-444c-bca2-40eb7fa2bca2">

2023-07-18 19:26 UTC, narayan954 commented on src/App.jsx
> +            <Darkmode theamClass="theamButton theamButton-login" />
broo, please use proper spellings, theme instead of theam, all over

2023-07-18 19:27 UTC, narayan954 commented on src/App.jsx
> +            <Darkmode theamClass="theamButton theamButton-login" />
also, why is this duplicate, you could've just used `or` operator

2023-07-18 19:34 UTC, narayan954 requested changes
please fix the naming conventions

2023-07-18 19:34 UTC, narayan954 commented on src/reusableComponents/Darkmode/index.jsx
> +      <div className="">
empty classnames?

2023-07-18 19:34 UTC, narayan954 commented on src/index.css
> +
empty style?

2023-07-19 05:13 UTC, biplavmz commented
ok @narayan954

2023-07-19 07:13 UTC, closed without merging