setup pagination for chat room
narayan954/dummygram pull request #985
Opened 2023-07-26 16:59 UTC by Palakkgoyal

This PR closes issue no. #936 
I have added pagination on the chat room and also made it scroll from bottom to top.

2023-07-26 21:43 UTC, narayan954 requested changes
could this usage be due to this?? If so this could be alarming actually.
![image](https://github.com/narayan954/dummygram/assets/77617189/4ccf2f17-bb99-46b2-8b17-b92699352dcd)

Also, there're many snapshots in our project which are not unsubscribed/closed. We need to lookout again for the db usage. I think before this chat feature, usage was fine...If we allow this pagination, it'd cross the limit very early tomorrow as there'd be more users. 


As now I am thinking, maybe this usage is partly because the snapshot is not closed and chat gets updated in background of users,once he has entered the chat section.It's like opening a portal lol on opening chat page. and partly because the pagination loads the chat very aggressively.

We need to add unsubscribe function in the return() of these component lifecycle.
I was just going to read [this article](https://blog.logrocket.com/how-to-use-react-hooks-firebase-firestore/) regarding firebase today only, maybe you can give it a read as well :)

2023-07-26 21:46 UTC, narayan954 commented
I think adding unsubscribe method should work, and this pagination is fine as well. If we get into a problem with this though, we can add pagination to be not on scroll but a button `load more`

2023-07-27 07:40 UTC, Palakkgoyal commented
> I think adding unsubscribe method should work, and this pagination is fine as well. If we get into a problem with this though, we can add pagination to be not on scroll but a button `load more`

I knew that providing a cleanup function is important but due to lack of experience I was not able to grasp its importance. After watching this and reading more about it I understand why it is important. I will do the required changes in it. Should I add a button now for loading chats or not?

2023-07-27 16:26 UTC, narayan954 commented
> > I think adding unsubscribe method should work, and this pagination is fine as well. If we get into a problem with this though, we can add pagination to be not on scroll but a button `load more`
> 
> I knew that providing a cleanup function is important but due to lack of experience I was not able to grasp its importance. After watching this and reading more about it I understand why it is important. I will do the required changes in it. Should I add a button now for loading chats or not?

it's your call, if it doesn't seem like it, let it be,else you definitely can! :)

2023-07-28 08:35 UTC, Palakkgoyal commented
I have done the required changes. Can you please check.

2023-07-28 18:03 UTC, narayan954 commented
> I have done the required changes. Can you please check.

aight, on it!

2023-07-28 18:04 UTC, narayan954 commented on src/components/CommunityChat/index.jsx
> -  }, [db]); // TODO - won't this cause infinite calling/refreshing if the db is under use / always changing?
now after removing, I'm thinking , it wont be a live chat, right?

2023-07-28 18:25 UTC, narayan954 approved these changes
looks good to me!

2023-07-28 18:26 UTC, merged

2023-07-28 18:38 UTC, narayan954 commented
Wait, does it work at all @Palakkgoyal ;-; I missed to check and now on production, I don't think it works ;-;

2023-07-29 06:56 UTC, Palakkgoyal commented
I checked it worked but I don't know about the production.

2023-07-29 09:28 UTC, narayan954 commented
> I checked it worked but I don't know about the production.

yes it works there, but doesn't at all in production version.

2023-07-29 13:52 UTC, Palakkgoyal commented
I tried to give a good cleanup to it using AbortController but don't know why it was not working.

2023-07-29 14:08 UTC, narayan954 commented
> I tried to give a good cleanup to it using AbortController but don't know why it was not working.

now I think abortcontroller is what's causing it to abort.

2023-07-29 15:07 UTC, Palakkgoyal commented
But I didn't used it cause AbortController wasn't even working during development.

2023-07-30 07:49 UTC, narayan954 commented
> But I didn't used it cause AbortController wasn't even working during development.

lol, btw in mobile devices, the feature work, but not in desktops... I'll go through the code again and try to fix as well

2023-07-30 13:02 UTC, Palakkgoyal commented
> > But I didn't used it cause AbortController wasn't even working during development.
> 
> lol, btw in mobile devices, the feature work, but not in desktops... I'll go through the code again and try to fix as well

Is it? That's seems typical.

2023-07-30 15:27 UTC, narayan954 commented
> > > But I didn't used it cause AbortController wasn't even working during development.
> > 
> > 
> > lol, btw in mobile devices, the feature work, but not in desktops... I'll go through the code again and try to fix as well
> 
> Is it? That seems typical.

I feel the same, but it worked ;-;

2023-07-30 19:30 UTC, Palakkgoyal commented
That's amazing.